"""Shared protocols, types, results, metadata, and diagnostics."""

from chaos_numerics.core.exceptions import (
    ChaosNumericsError,
    ChaosNumericsWarning,
    ConvergenceError,
    ConvergenceWarning,
    NumericalError,
    NumericalWarning,
    ReproducibilityWarning,
    ValidationError,
)
from chaos_numerics.core.metadata import ConvergenceInfo, Diagnostic, ExperimentMetadata
from chaos_numerics.core.protocols import (
    ClassicalMap,
    Flow,
    LinearOperatorLike,
    Partition,
    QuantumMap,
)
from chaos_numerics.core.results import AnalysisResult, EigenstateResult, Spectrum, Trajectory
from chaos_numerics.core.types import (
    ArrayLike,
    BatchShape,
    BoolArray,
    ClassicalBatch,
    ClassicalState,
    ComplexArray,
    FloatArray,
    IndexArray,
    OperatorArray,
    OperatorShape,
    QuantumBatch,
    QuantumState,
    Shape,
    StateShape,
)

__all__ = [
    "AnalysisResult",
    "ArrayLike",
    "BatchShape",
    "BoolArray",
    "ChaosNumericsError",
    "ChaosNumericsWarning",
    "ClassicalBatch",
    "ClassicalMap",
    "ClassicalState",
    "ComplexArray",
    "ConvergenceError",
    "ConvergenceInfo",
    "ConvergenceWarning",
    "Diagnostic",
    "EigenstateResult",
    "ExperimentMetadata",
    "FloatArray",
    "Flow",
    "IndexArray",
    "LinearOperatorLike",
    "NumericalError",
    "NumericalWarning",
    "OperatorArray",
    "OperatorShape",
    "Partition",
    "QuantumBatch",
    "QuantumMap",
    "QuantumState",
    "ReproducibilityWarning",
    "Shape",
    "Spectrum",
    "StateShape",
    "Trajectory",
    "ValidationError",
]
